/**
 * Seed CRM with leads from the Lima SMB Digital Transformation report.
 * Run: npx tsx scripts/seed.ts
 */
import { Pool } from 'pg'
import { config } from 'dotenv'

config({ path: '.env.local' })

const pool = new Pool({ connectionString: process.env.DATABASE_URL })

type Lead = {
  name: string
  district: string
  niche: string
  category?: string
  instagram_active?: boolean
  website_status?: string
  evaluation?: string
  strategic_action?: string
  potential?: string
}

// ---------- Table 1: Gastronomy ----------
const gastronomy: Array<[string, string, boolean, string, string, string]> = [
  ['Locos por el Asado', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Independent Booking Engine'],
  ['Mattoni', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Conversion UI Build'],
  ['Bistro 400', 'Miraflores', true, 'Outdated', 'Unfit (Slow Load)', 'Full Redesign + Monitoring'],
  ['KIMO', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Luxury Experience Build'],
  ['Festivo', 'Miraflores', true, 'No Website', 'Absent', 'Full Brand Site Build'],
  ['Quipas', 'Miraflores', true, 'No Website', 'Absent', 'Authority Building Site'],
  ['Contraste', 'Miraflores', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Citron', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Direct Booking Portal'],
  ['Pitahaya Lounge', 'Miraflores', true, 'Platform-Only', 'Unfit (Mobile)', 'Events & Nightlife UX'],
  ['Amankaya', 'Miraflores', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Flama', 'Miraflores', true, 'No Website', 'Absent', 'Digital Menu & Booking'],
  ['Dhaasu', 'Miraflores', true, 'No Website', 'Absent', 'Cultural Storytelling Site'],
  ['I-baigo', 'Miraflores', true, 'No Website', 'Absent', 'Bar & Tapas Brand Build'],
  ['Ché Chá Food & Bar', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Full Web Identity'],
  ['Omatsu Nikkei', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'High-End Portfolio Build'],
  ['Chifa Lung Fung', 'San Isidro', true, 'No Website', 'Absent', 'Heritage Brand Site'],
  ['BUCHE', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Corporate Lunch UX Build'],
  ['500 Grados', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'High-Volume Booking Site'],
  ['Gaijin', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Reservation System Build'],
  ['Brass Grill and Bar', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Full Web Build'],
  ['Popular - San Isidro', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Conversion Optimization'],
  ['Celeste Solar Bar', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Event Management Portal'],
  ['Isidro Bistró Limeño', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Direct Booking Build'],
  ['Bahía Lima', 'San Isidro', true, 'Outdated', 'Unfit (Static)', 'UI/UX Update + Monitoring'],
  ['ADN Pisco', 'Santiago de Surco', true, 'No Website', 'Absent', 'Full Brand Site Build'],
  ['Bisonte Casa Brava', 'Santiago de Surco', true, 'No Website', 'Absent', 'Digital Trust Build'],
  ['Cafeina Gourmet', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'E-commerce Store (Coffee)'],
  ['DON MELCHOR', 'Santiago de Surco', true, 'No Website', 'Absent', 'Lead Generation Site'],
  ['Don Tito - Surco', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Fast Casual Ordering'],
  ['Donde Felipe', 'Santiago de Surco', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Doomo Saltado - Surco', 'Santiago de Surco', true, 'Outdated', 'Unfit (Performance)', 'Full Modernization'],
  ['Franklin Kitchen & Bar', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Reservation UX Build'],
  ['Granja Azul El Polo', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Heritage Optimization'],
  ['KION', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Direct Booking Build'],
  ['Kyoto - El Polo', 'Santiago de Surco', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Oscar Lorenzo Cafe', 'Santiago de Surco', true, 'No Website', 'Absent', 'Cafe Experience Site'],
  ['The Coffee - El Golf', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Loyalty Program Site'],
  ['Pescados Capitales', 'San Borja', true, 'Outdated', 'Unfit (Mobile)', 'Full UX Modernization'],
  ['La Nacional', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Conversion Build'],
  ['Los Rolls de Diego', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Online Ordering Portal'],
  ['Reiwa Izakaya', 'San Borja', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Stragos - Aviación', 'San Borja', true, 'No Website', 'Absent', 'Nightlife Events Site'],
  ['Don Tito - San Borja', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Delivery Integration'],
  ['Viet', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Exotic Food Storytelling'],
  ['Mamma Tomato', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Delivery UX Build'],
  ['El Tambo II', 'La Molina', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Puerto Mancora', 'La Molina', true, 'Platform-Only', 'Needs Dedicated Site', 'Direct Booking Portal'],
  ['Sala Omakase', 'La Molina', true, 'No Website', 'Absent', 'Exclusive Booking Portal'],
  ['La Plazita', 'La Molina', true, 'Platform-Only', 'Needs Dedicated Site', 'Mediterranean Branding'],
  ['El Charrua', 'La Molina', true, 'Outdated', 'Unfit (Security)', 'Full Site Rebuild'],
  ['Farmer Chicken & Co', 'La Molina', true, 'No Website', 'Absent', 'Delivery & Brand Build'],
  ['La Nevera Fit', 'La Molina', true, 'Platform-Only', 'Needs Dedicated Site', 'Healthy E-commerce'],
  ['Sabha Gourmet', 'La Molina', true, 'No Website', 'Absent', 'Full Brand Build'],
  ['Mamaq Sal de Maras', 'La Molina', true, 'Platform-Only', 'Needs Dedicated Site', 'D2C E-commerce'],
  ['Cumpa Taberna', 'Miraflores', true, 'No Website', 'Absent', 'Traditional Brand Build'],
  ['Fernandini', 'Barranco/Miraflores', true, 'No Website', 'Absent', 'Signature Web Identity'],
  ['Seitan Urban Bistro', 'Miraflores', true, 'No Website', 'Absent', 'Vegan Lifestyle Site'],
  ['Naia Cafe', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Cafe Booking Site'],
  ['Colonia & Co', 'Barranco/Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Experience Branding'],
  ['Isolina', 'Barranco/Miraflores', true, 'Outdated', 'Unfit (Reservations)', 'High-Performance Rebuild'],
  ['Caudalia', 'Miraflores', true, 'No Website', 'Absent', 'Luxury Dining Site'],
  ['Sabina', 'Miraflores', true, 'No Website', 'Absent', 'Direct Reservation Portal'],
  ['Clon', 'Miraflores', true, 'No Website', 'Absent', 'Contemporary Web Presence'],
  ['El Jardín', 'Miraflores', true, 'No Website', 'Absent', 'Visual Experience Build'],
  ['Ancestral', 'Miraflores', true, 'No Website', 'Absent', 'Heritage Brand Build'],
  ['Vaca Negra', 'Miraflores', true, 'No Website', 'Absent', 'Burger Delivery UX'],
  ['Somos Ana', 'Miraflores', true, 'No Website', 'Absent', 'Bar Events System'],
  ['Black Birds', 'Miraflores', true, 'No Website', 'Absent', 'Nightlife Marketing'],
  ['Damian', 'Miraflores', true, 'No Website', 'Absent', 'High-End Bar Web'],
  ['PesCo Pescaderia', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Seafood E-commerce'],
  ['Vecino Pizzas', 'Miraflores', true, 'No Website', 'Absent', 'Hyper-Local Delivery Site'],
  ['Crudo Cocina', 'Miraflores', true, 'No Website', 'Absent', 'Technical Dining Site'],
  ['Perro Gato Pericote', 'Miraflores', true, 'No Website', 'Absent', 'Pet-Friendly Branding'],
  ['Ototo', 'San Isidro', true, 'No Website', 'Absent', 'Modern Nikkei Site'],
  ['Uke Handroll Bar', 'San Isidro', true, 'No Website', 'Absent', 'Specialized Sushi Site'],
  ['Matsuei', 'Miraflores', true, 'Outdated', 'Unfit (UI)', 'Full Modernization'],
  ['Makoto', 'Miraflores', true, 'Outdated', 'Unfit (Booking)', 'Performance Rebuild'],
  ['Hiro Japanese', 'Miraflores', true, 'No Website', 'Absent', 'Traditional Portfolio Site'],
  ['Kayzen Sushi', 'Miraflores', true, 'No Website', 'Absent', 'Fast Casual Ordering'],
  ['LIMO Nikkei', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Full Web Build'],
  ['Bar Italiano Trattoria', 'Miraflores', true, 'Outdated', 'Unfit (Static)', 'Direct Reservation Site'],
  ['Trattoria Don Vito', 'Miraflores', true, 'Outdated', 'Unfit (Mobile)', 'Full Rebuild'],
  ['KOBE', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Luxury Brand Build'],
  ['Osso', 'San Isidro', true, 'Outdated', 'Unfit (Performance)', 'Performance Optimization'],
  ['Tierra del Fuego', 'Miraflores', true, 'Outdated', 'Unfit (Design)', 'Modern Steakhouse UX'],
  ['La Cabrera', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Global Brand Localized'],
  ['La Vaca Loca', 'Miraflores', true, 'Outdated', 'Unfit (Mobile)', 'Full UI Redesign'],
  ['El 10 Miraflores', 'Miraflores', true, 'No Website', 'Absent', 'Brand Trust Site'],
  ['Kilo', 'Miraflores', true, 'Outdated', 'Unfit (Booking)', 'Reservation Rebuild'],
  ['Donde Walter', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Local Authority Build'],
  ['La Picante', 'Miraflores', true, 'No Website', 'Absent', 'Spicy Seafood Brand'],
  ['La Isla Escondida', 'Santiago de Surco', true, 'No Website', 'Absent', 'Secret Dining Portal'],
  ['Alfresco', 'Miraflores', true, 'Outdated', 'Unfit (UX)', 'High-Traffic Rebuild'],
  ['Mi Propiedad Privada', 'Miraflores', true, 'Outdated', 'Unfit (Design)', 'Full Modernization'],
  ['Costazul Seafood', 'Miraflores', true, 'Outdated', 'Unfit (Speed)', 'Performance Build'],
  ['Merit', 'Miraflores', true, 'No Website', 'Absent', 'Signature Web Identity'],
  ['Merlín', 'Miraflores', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Haagen Dazs', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Retail Loyalty Site'],
  ['Mozart', 'San Borja', true, 'Outdated', 'Unfit (Security)', 'Full E-commerce Rebuild'],
]

// ---------- Table 2: Professional Services / Lawyers ----------
const legal: Array<[string, string, boolean, string, string, string]> = [
  ['Angulo Portocarrero', 'San Isidro', false, 'Outdated', 'Unfit (Static)', 'Secure Portal + Redesign'],
  ['Canessa & Núñez', 'San Isidro', false, 'Outdated', 'Unfit (Mobile)', 'Full Modernization'],
  ['Estudio Ghersi', 'San Isidro', false, 'Outdated', 'Unfit (UI)', 'Authority Site Rebuild'],
  ['Estudio Villegas', 'San Isidro', false, 'No Website', 'Absent', 'Full Digital ID Build'],
  ['Orihuela Abogados', 'San Isidro', false, 'Outdated', 'Unfit (UX)', 'Lead Gen Optimization'],
  ['Rebaza, Alcazar', 'San Isidro', false, 'Outdated', 'Unfit (Design)', 'Modern Corporate UI'],
  ['Antoinette Carrillo', 'Miraflores', true, 'Outdated', 'Unfit (Conversion)', 'Immigration Portal UX'],
  ['Espinoza Law Offices', 'Miraflores', false, 'Outdated', 'Unfit (Security)', 'Secure Communications Build'],
  ['Salazar Gamarra', 'Miraflores', false, 'Outdated', 'Unfit (Mobile)', 'Responsive Rebuild'],
  ['Guillermo Velarde', 'San Isidro', false, 'No Website', 'Absent', 'Digital Presence Build'],
  ['Flores-Araoz', 'San Isidro', false, 'Outdated', 'Unfit (UI)', 'Political/Legal Authority'],
  ['Alvarez Calderón', 'Miraflores', false, 'Outdated', 'Unfit (Static)', 'Professional Rebuild'],
  ['Abarca Abogados', 'San Isidro', false, 'No Website', 'Absent', 'Full Digital ID Build'],
  ['Muniz Law', 'San Isidro', true, 'Outdated', 'Unfit (Speed)', 'Performance Optimization'],
  ['Rodrigo, Elias', 'San Isidro', false, 'Outdated', 'Unfit (UX)', 'High-End Corporate UI'],
  ['Salinas & Tamayo', 'San Isidro', false, 'Outdated', 'Unfit (Security)', 'Secure Legal Portal'],
  ['Luna Abogados', 'San Isidro', false, 'No Website', 'Absent', 'Full Web Build'],
  ['CV Legal', 'San Isidro', true, 'No Website', 'Absent', 'Lead Gen Site Build'],
  ['Cervantes Fernandez', 'San Isidro', false, 'No Website', 'Absent', 'Small Practice Site'],
  ['Delgado Pacheco', 'San Isidro', false, 'Outdated', 'Unfit (Mobile)', 'Responsive Rebuild'],
  ['Monteblanco Law', 'Miraflores', true, 'Outdated', 'Unfit (UX)', 'International Law UI'],
  ['Obregon Ramirez', 'Miraflores', false, 'No Website', 'Absent', 'Full Web Build'],
  ['Estudio Juridico 21', 'San Isidro', true, 'Platform-Only', 'Needs Dedicated Site', 'Direct Client Booking'],
  ['Maurcio Olaya', 'San Isidro', true, 'No Website', 'Absent', 'Personal Brand Site'],
  ['Fernando Meléndez', 'San Isidro', false, 'No Website', 'Absent', 'Legal Authority Build'],
  ['Daniel Ono Hirata', 'San Isidro', false, 'No Website', 'Absent', 'Tax Law Specialized Site'],
  ['Ricardo Herrera', 'San Isidro', true, 'No Website', 'Absent', 'Labor Law Portal'],
  ['Yuri Vega Mere', 'San Isidro', false, 'No Website', 'Absent', 'Corporate Law Branding'],
  ['María del Pilar Flórez', 'San Isidro', false, 'No Website', 'Absent', 'Professional Site Build'],
  ['Jorge Otoya', 'San Isidro', false, 'No Website', 'Absent', 'Education Law Portal'],
]

// ---------- Table 3: Beauty Salons & Spas ----------
const beauty: Array<[string, string, boolean, string, string, string]> = [
  ['Franick Salon', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Integrated Booking UX'],
  ['Rojo Salon', 'San Borja', true, 'Platform-Only', 'Needs Dedicated Site', 'Visual Portfolio Site'],
  ['Paredes Bustamante', 'San Borja', true, 'No Website', 'Absent', 'Full Brand Site'],
  ['Salon Unisex Anny', 'San Borja', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Maki Color Spa', 'San Borja', true, 'No Website', 'Absent', 'Luxury Spa Portal'],
  ['Sulca Lagos', 'San Borja', true, 'No Website', 'Absent', 'Personal Brand Site'],
  ['Montalvo Salon', 'San Borja', true, 'Outdated', 'Unfit (Performance)', 'Performance Rebuild'],
  ['Tu Stylo Salon', 'San Borja', true, 'No Website', 'Absent', 'Visual Conversion Build'],
  ["D'Paula", 'San Borja', true, 'No Website', 'Absent', 'Local SEO & Web Build'],
  ['Belleza & Punto', 'San Borja', true, 'No Website', 'Absent', 'Appointment Portal'],
  ['Le Chic Salon', 'San Borja', true, 'No Website', 'Absent', 'Luxury UI Build'],
  ['La Voire Spa', 'San Borja', true, 'No Website', 'Absent', 'Treatment Catalog Site'],
  ['Backstage Salon', 'San Borja', true, 'No Website', 'Absent', 'Portfolio Site Build'],
  ['Anne Salon', 'San Borja', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Imagenes', 'San Borja', true, 'No Website', 'Absent', 'Stylist Showcase Build'],
  ['Las Vegas Salon', 'San Borja', true, 'No Website', 'Absent', 'Full Digital Presence'],
  ['Voga Salon', 'San Borja', true, 'No Website', 'Absent', 'Full Web Build'],
  ['X-Pert-Easy', 'San Borja', true, 'No Website', 'Absent', 'Efficiency Branding'],
  ['Glam Hair Concept', 'San Borja', true, 'No Website', 'Absent', 'Full Visual Web'],
  ['Urban Colors', 'San Borja', true, 'No Website', 'Absent', 'Modern Colorist Site'],
  ['Blossom Beauty', 'San Borja', true, 'Outdated', 'Unfit (UX)', 'Booking Engine Rebuild'],
  ['Belleza Peruana', 'San Borja', true, 'Outdated', 'Unfit (Security)', 'Medical Esthetics Portal'],
  ['Soho Color', 'Miraflores', true, 'Outdated', 'Unfit (Speed)', 'High-Performance UX'],
  ['Motivos Spa', 'La Molina', true, 'Platform-Only', 'Needs Dedicated Site', 'Multi-Sede Management'],
  ['Urban Colors (Miraflores)', 'Miraflores', true, 'No Website', 'Absent', 'Full Brand Build'],
  ['Rojo Salon (Miraflores)', 'Miraflores', true, 'No Website', 'Absent', 'Portfolio Rebuild'],
  ['Le Voire', 'San Isidro', true, 'No Website', 'Absent', 'Luxury Spa Branding'],
  ['Backstage', 'San Isidro', true, 'No Website', 'Absent', 'High-End Portfolio'],
  ['Las Vegas', 'San Isidro', true, 'No Website', 'Absent', 'Professional Brand Site'],
  ['Anne Salon (San Isidro)', 'San Isidro', true, 'No Website', 'Absent', 'Full Digital ID'],
]

// ---------- Table 4: Automotive ----------
const automotive: Array<[string, string, boolean, string, string, string]> = [
  ['ASB Motors', 'Santiago de Surco', true, 'Platform-Only', 'Needs Dedicated Site', 'Specialist Authority Site'],
  ['Europa Service', 'Santiago de Surco', true, 'Outdated', 'Unfit (Mobile)', 'Responsive UX Build'],
  ['LM Motors', 'Santiago de Surco', false, 'No Website', 'Absent', 'Full Digital Presence'],
  ['Fiocco Hnos', 'Santiago de Surco', false, 'No Website', 'Absent', 'Heritage Brand Site'],
  ['Intihuatana Motors', 'Santiago de Surco', false, 'No Website', 'Absent', 'Service Portal Build'],
  ['Wigo Motors', 'Santiago de Surco', true, 'Outdated', 'Unfit (Speed)', 'High-Performance UI'],
  ['Galecc Service', 'Santiago de Surco', false, 'No Website', 'Absent', 'Technical Specs Site'],
  ['Toyo Service', 'Santiago de Surco', false, 'No Website', 'Absent', 'Japanese Specialist Site'],
  ['Transmotores', 'Chorrillos/Surco', true, 'No Website', 'Absent', 'Full Web Build'],
  ['Audi Zentrum', 'Santiago de Surco', true, 'Outdated', 'Unfit (Performance)', 'Luxury Performance Site'],
  ['Motormundo', 'Santiago de Surco', true, 'Outdated', 'Unfit (UX)', 'Multi-Brand Portal'],
  ['Autoland', 'Santiago de Surco', true, 'Outdated', 'Unfit (Mobile)', 'Full Responsive Build'],
  ['Autoniza', 'Santiago de Surco', true, 'No Website', 'Absent', 'Brand Trust Site Build'],
  ['León Autos', 'Santiago de Surco', false, 'No Website', 'Absent', 'Specialized Landing Page'],
  ['V Motor Center', 'La Molina', true, 'No Website', 'Absent', 'Full Digital ID Build'],
  ['Limautos', 'Santiago de Surco', true, 'Outdated', 'Unfit (Speed)', 'Inventory Engine Build'],
  ['Peñaranda Planchado', 'Surquillo/Surco', true, 'No Website', 'Absent', 'Visual Portfolio Site'],
  ['Planeta Motors', 'Santiago de Surco', false, 'No Website', 'Absent', 'Local Service Site'],
  ['Revo Motors', 'Santiago de Surco', true, 'No Website', 'Absent', 'High-End Tuning Site'],
  ['Euromotors', 'Santiago de Surco', true, 'Outdated', 'Unfit (UX)', 'European Car Specialist Site'],
  ['Corfigas Ingenieros', 'Santiago de Surco', true, 'Outdated', 'Unfit (Design)', 'Engineering Authority Site'],
  ['Mecánicos a Domicilio', 'Santiago de Surco', true, 'Outdated', 'Unfit (Conversion)', 'Emergency 24/7 Portal'],
  ['Cordaez Performance', 'Santiago de Surco', true, 'Outdated', 'Unfit (Static)', 'Performance Tuning UI'],
  ['Taller Corfigas', 'Santiago de Surco', true, 'No Website', 'Absent', 'Service Catalog Build'],
  ['Mega Autos', 'Santiago de Surco', false, 'No Website', 'Absent', 'Full Web Build'],
  ['Germania Automotriz', 'Santiago de Surco', true, 'No Website', 'Absent', 'German Specialist Branding'],
  ['Toyo Service Maranga', 'Santiago de Surco', false, 'No Website', 'Absent', 'Japanese Car Authority'],
  ['Transmotores Campiña', 'Santiago de Surco', false, 'No Website', 'Absent', 'Service Logistics Web'],
  ['Motormundo Colonia', 'Santiago de Surco', true, 'No Website', 'Absent', 'Full Digital Build'],
  ['Wigo República', 'San Isidro', true, 'No Website', 'Absent', 'Full Brand Identity'],
]

// ---------- Table 5: Fitness ----------
const fitness: Array<[string, string, boolean, string, string, string]> = [
  ['Smart Fit', 'Miraflores', true, 'Outdated', 'Unfit (UX)', 'Localized Membership Portal'],
  ['BIGG', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Community & Booking Engine'],
  ['Gimnasio B2', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Class Scheduling Build'],
  ['Trim Gym', 'Miraflores', true, 'No Website', 'Absent', 'Full Web Brand Identity'],
  ['Arcade S.A.', 'Miraflores', false, 'No Website', 'Absent', 'Full Fitness Portal'],
  ['KO Urban Detox', 'Miraflores', true, 'Outdated', 'Unfit (Speed)', 'Wellness Platform Build'],
  ['Lima Float', 'Miraflores', true, 'Platform-Only', 'Needs Dedicated Site', 'Booking & Experience Site'],
  ['Brox', 'Miraflores', true, 'No Website', 'Absent', 'Full Gym Site Build'],
  ['Chino Vásquez', 'Miraflores', false, 'Platform-Only', 'Needs Dedicated Site', 'Community Sports Hub'],
  ['Skate Park Miraflores', 'Miraflores', true, 'No Website', 'Absent', 'Event & Safety Portal'],
  ['Centro Tenis Mira', 'Miraflores', false, 'No Website', 'Absent', 'Court Reservation System'],
  ['Niño Héroe Bonilla', 'Miraflores', false, 'No Website', 'Absent', 'Facility Booking Site'],
  ['KO La Molina', 'La Molina', true, 'No Website', 'Absent', 'Localized Fitness Branding'],
  ['KO San Borja', 'San Borja', true, 'No Website', 'Absent', 'Full Web Rebuild'],
  ['Smart Fit San Isidro', 'San Isidro', true, 'Outdated', 'Unfit (Mobile)', 'Local SEO & Conversion'],
  ['Trim Gym Surco', 'Santiago de Surco', true, 'No Website', 'Absent', 'Full Brand Launch Site'],
  ['BIGG San Isidro', 'San Isidro', true, 'No Website', 'Absent', 'Membership Experience Build'],
  ['KO Jockey Plaza', 'Santiago de Surco', true, 'No Website', 'Absent', 'Retail Fitness Site'],
  ['Brox Lima', 'San Isidro', true, 'No Website', 'Absent', 'Authority Fitness Build'],
  ['Trim Gym La Molina', 'La Molina', true, 'No Website', 'Absent', 'Localized Digital Strategy'],
]

// ---------- Table 6: Industrial & Commercial (different shape: Category + Potential) ----------
const industrial: Array<[string, string, string, string, string]> = [
  // [name, district, category, websiteStatus, potential]
  ['ACKER ACKER', 'San Isidro', 'Trade', 'Absent', 'Full Web Build'],
  ['MERCY S.R.L.', 'San Isidro', 'Services', 'Absent', 'Service Portal'],
  ['CERAMICA LIMA', 'Santiago de Surco', 'Manufacture', 'Outdated', 'Industrial UX Build'],
  ['CORPORACION CERAMICA', 'Santiago de Surco', 'Manufacture', 'Outdated', 'Catalog Modernization'],
  ['GRUPO ACRIMSA', 'San Borja', 'Services', 'Absent', 'Professional Brand Build'],
  ['ACROW PERU S.A.', 'Miraflores', 'Construction', 'Outdated', 'Technical Portfolio'],
  ['ADFINSA S.A.', 'Miraflores', 'Finance', 'Absent', 'Full Digital ID'],
  ['5 C SERVICIOS', 'Miraflores', 'Services', 'Absent', 'Lead Gen Site'],
  ['CINCO CLEANERS', 'Miraflores', 'Services', 'Absent', 'Local Service Web'],
  ['ADG & ASOCIADOS', 'Miraflores', 'Consulting', 'Absent', 'Full Web Build'],
  ['AEI INGENIEROS', 'San Isidro', 'Engineering', 'Absent', 'Technical Brand Build'],
  ['AERO ANDINO', 'Miraflores', 'Aviation', 'Absent', 'Full Web Build'],
  ['AERO CONTINENTE', 'Miraflores', 'Travel', 'Absent', 'Booking Portal'],
  ['AGROFIOT', 'Miraflores', 'Agriculture', 'Absent', 'B2B Portal'],
  ['AERO MEXICO', 'Miraflores', 'Travel', 'Outdated', 'Local SEO Optimization'],
  ['AERONAUTICA S.A.', 'Santiago de Surco', 'Aviation', 'Absent', 'Full Web Build'],
  ['AEROPARACAS S.A.', 'Miraflores', 'Travel', 'Absent', 'Tourism Experience Site'],
  ['GALLARDO MELLADO', 'Santiago de Surco', 'Services', 'Absent', 'Full Digital ID'],
  ['AGE S.A.', 'Santiago de Surco', 'General', 'Absent', 'Professional Build'],
  ['BBDO PERU S.A.', 'Miraflores', 'Agency', 'Outdated', 'Visual Performance Site'],
  ['TURISTRAVEL S.A.', 'Miraflores', 'Travel', 'Absent', 'Dynamic Booking Web'],
  ['ALFREDO GRAF', 'San Isidro', 'Real Estate', 'Outdated', 'Listing Engine Build'],
  ['ALEXANDER GRAHAM BELL', 'Miraflores', 'Tech', 'Absent', 'Innovation Brand Site'],
  ['AGROINDUSTRIAS ANDINAS', 'La Molina', 'Agri', 'Absent', 'Export Portal'],
  ['AGROFOR S.A.', 'San Isidro', 'Agri', 'Absent', 'Full Web Build'],
  ['AGRO INDUSTRIAS EMIC', 'La Molina', 'Agri', 'Absent', 'Industrial Catalog'],
  ['AGROINDUSTRIAS UNIDAS', 'San Isidro', 'Agri', 'Absent', 'Supply Chain Site'],
  ['AGROKASA', 'Miraflores', 'Agri', 'Outdated', 'Corporate Modernization'],
  ['AGROSAN S.A.C.', 'San Borja', 'Agri', 'Absent', 'Full Web Build'],
  ['AGRO STAFF S.R.L.', 'Santiago de Surco', 'Agri', 'Absent', 'Professional Site'],
  ['AGRO-SYSTEMS', 'Santiago de Surco', 'Agri', 'Absent', 'Tech Specs Site'],
  ['AGENCIA SANTA ISABEL', 'Santiago de Surco', 'Trade', 'Absent', 'Full Web Build'],
  ['DISTRIBUIDORA AGUIRRE', 'La Molina', 'Trade', 'Absent', 'Distribution Portal'],
  ['AGUPLAST E.I.R.L.', 'La Molina', 'Industrial', 'Absent', 'Product Catalog Site'],
  ['MC LARENS TOPLIS', 'Santiago de Surco', 'Services', 'Absent', 'Corporate Build'],
  ['AGROVET MARKET', 'San Isidro', 'Pharma', 'Outdated', 'Product Database Site'],
  ['KNIGHT DEL PERU', 'San Isidro', 'Services', 'Absent', 'Full Web Build'],
  ['AHSECO PERU S.A.', 'San Borja', 'Medical', 'Absent', 'Full Digital ID'],
  ['AIDA SOLARI', 'Miraflores', 'Professional', 'Absent', 'Authority Build'],
  ['AID INGENIEROS', 'Miraflores', 'Engineering', 'Absent', 'Technical Showcase'],
  ['AMERICAN INDUSTRIAL', 'Miraflores', 'Industrial', 'Absent', 'Equipment Sales Site'],
  ['AIRTEC S.A.', 'Santiago de Surco', 'Industrial', 'Absent', 'Technical Specs Site'],
  ['AIRTECNIA S.R.L.', 'Santiago de Surco', 'Industrial', 'Absent', 'Full Web Build'],
  ['AIS EXPORT IMPORT', 'San Isidro', 'Trade', 'Absent', 'Export Dashboard Build'],
  ['AISLAMIENTOS IND.', 'Santiago de Surco', 'Industrial', 'Absent', 'Technical Brand Build'],
  ['TRANSTECHNOLOGY', 'Miraflores', 'Tech', 'Absent', 'Innovation Portal'],
  ['AJM INGENIEROS', 'Miraflores', 'Engineering', 'Absent', 'Full Web Build'],
  ['AKL CONSTRUCTORA', 'Santiago de Surco', 'Construction', 'Absent', 'Portfolio & Leads'],
  ['ALANCO PERU S.A.', 'Miraflores', 'Services', 'Absent', 'Full Digital ID'],
  ['POWER COMPUTER', 'Santiago de Surco', 'Tech', 'Absent', 'E-commerce Store'],
  ['ALANPER CICEX S.A.', 'Santiago de Surco', 'Trade', 'Absent', 'Full Web Build'],
  ['PATZY S.A.C.', 'Santiago de Surco', 'Trade', 'Absent', 'Online Inventory'],
  ['GECE S.A.C.', 'San Borja', 'Trade', 'Absent', 'Full Brand Site'],
  ['FOOD FOR LIFE', 'San Isidro', 'Food', 'Absent', 'Healthy E-commerce'],
  ['CURTIS & CO', 'San Isidro', 'Trade', 'Absent', 'Professional Build'],
  ['LS ANDINA SA', 'San Isidro', 'Trade', 'Absent', 'Corporate Web Build'],
  ['VINA TACAMA', 'San Isidro', 'Food/Bev', 'Outdated', 'High-End Storytelling'],
  ['CORPORACION VEGA', 'San Borja', 'Retail', 'Outdated', 'Modern E-commerce'],
  ['EXTRAGEL Y UNIVERSAL', 'San Borja', 'Food', 'Absent', 'Full Web Build'],
  ['MOLITALIA S.A.', 'San Borja', 'Food', 'Outdated', 'Performance Rebuild'],
  ['BLACK Y DECKER', 'Santiago de Surco', 'Tools', 'Outdated', 'Local SEO Focus'],
  ['CROSSPOINTE PERU', 'San Borja', 'Industrial', 'Absent', 'Technical Showcase'],
  ['ROSSINI MARBLE', 'Santiago de Surco', 'Construction', 'Absent', 'High-End Portfolio'],
  ['A Y A EDIFICACIONES', 'San Borja', 'Construction', 'Absent', 'Project Branding'],
  ['HYDRA INDUSTRIA', 'San Borja', 'Construction', 'Absent', 'Industrial Build'],
  ['MICROCEMENTO S.A.C.', 'San Borja', 'Construction', 'Absent', 'Specialty Portfolio'],
  ['DJAGO CONTRATISTAS', 'La Molina', 'Construction', 'Absent', 'Service Authority Build'],
  ['ART PROJECT', 'Miraflores', 'Construction', 'Absent', 'Artful UX Build'],
  ['TOPANIN S.A.C.', 'San Borja', 'Textiles', 'Absent', 'Industrial Branding'],
  ['LAVANDERIA LANDEO', 'San Borja', 'Services', 'Absent', 'Local Service Web'],
  ['CORPORACION VASCO', 'San Borja', 'Textiles', 'Absent', 'Full Web Build'],
  ['JORGE PENA S.A.', 'San Borja', 'Textiles', 'Absent', 'Heritage Brand Site'],
  ['KAPAROMA E.I.R.L.', 'San Borja', 'Textiles', 'Absent', 'Professional Site Build'],
  ['VICSATEX EIRL', 'San Borja', 'Textiles', 'Absent', 'Catalog Optimization'],
  ['E & M TEXTIL', 'San Borja', 'Textiles', 'Absent', 'Full Web Build'],
  ['HOPE SOLUTIONS', 'Santiago de Surco', 'Textiles', 'Absent', 'Business Services Site'],
  ['GENIAL BUSINESS', 'Miraflores', 'Textiles', 'Absent', 'Full Digital Presence'],
  ['MAFAB SERVICIOS', 'Miraflores', 'Textiles', 'Absent', 'Full Web Build'],
  ['SML PERU', 'Miraflores', 'Textiles', 'Absent', 'International UX Build'],
  ['LR ACCESORIOS', 'Miraflores', 'Textiles', 'Absent', 'Fashion E-commerce'],
  ['MALAGA BIJOU', 'Miraflores', 'Textiles', 'Absent', 'Retail Store Build'],
  ['QUEEN BEE TEXTIL', 'San Borja', 'Textiles', 'Absent', 'Brand Storefront'],
  ['VIDAL OBREGON', 'San Borja', 'Textiles', 'Absent', 'Personal Brand Site'],
  ['EXPORT IKAROS', 'San Borja', 'Textiles', 'Absent', 'Export Brand Build'],
  ['NEGOCIACIONES CARYDIAN', 'San Borja', 'Textiles', 'Absent', 'Trading Hub Web'],
  ['ROJAS CASTILLEJOS', 'Santiago de Surco', 'Automotive', 'Absent', 'Parts E-commerce'],
  ['TEJADA NUNEZ', 'Santiago de Surco', 'Automotive', 'Absent', 'Technical Services Site'],
  ['GRUPO DELTA MOTORS', 'Santiago de Surco', 'Automotive', 'Absent', 'High-End Sales UX'],
  ['PROJOSE GARCIA', 'Miraflores', 'Metal', 'Absent', 'Industrial Catalog'],
  ['GRUPO OPTICO MI OPTICA', 'La Molina', 'Health', 'Absent', 'Local SEO Web'],
  ['MACK PC', 'Miraflores', 'Tech', 'Absent', 'Repair Service Portal'],
  ['G&R SOLUCIONES', 'San Borja', 'Tech', 'Absent', 'Solution Architecture Web'],
  ['ALECOED SAC', 'Santiago de Surco', 'Food', 'Absent', 'Niche Food Branding'],
  ['SUPAY DEMONIO', 'La Molina', 'Food', 'Absent', 'Brand Identity Build'],
  ['MCB IMPORT EXPORT', 'San Isidro', 'Trade', 'Absent', 'International UI'],
  ["K'UMARA WAYU", 'La Molina', 'Health', 'Absent', 'Full Brand Site Build'],
  ['ACERINDUSTRIAS', 'San Borja', 'Industrial', 'Absent', 'Quote Request Site'],
  ['ACEROS OTERO', 'San Borja', 'Industrial', 'Absent', 'Technical Data Web'],
  ['CUTITON S.A.C.', 'San Borja', 'Industrial', 'Absent', 'Product Catalog Site'],
  ['PRO-SELLER S.C.R.L.', 'San Borja', 'Trade', 'Absent', 'Professional Trade UI'],
  ['JHL METALCON', 'San Borja', 'Metal', 'Absent', 'Construction Specs Site'],
  ['METAL GRAF S.R.L.', 'San Borja', 'Metal', 'Absent', 'Full Digital ID Build'],
  ['AQUA FLASH', 'San Borja', 'Services', 'Absent', 'Plumber Service Web'],
  ['SEAIRCORE', 'Santiago de Surco', 'Industrial', 'Absent', 'AC Service Portal'],
  ['COMPANIA CAMPORSAL', 'Santiago de Surco', 'Construction', 'Absent', 'Full Web Build'],
  ['SABHA GOURMET', 'La Molina', 'Food', 'Absent', 'Gourmet Store Build'],
  ['EXPOANDINA NEGOCIOS', 'La Molina', 'Trade', 'Absent', 'Export Authority Site'],
  ['COMFER S.A.', 'San Borja', 'Manufacture', 'Absent', 'Industry Presence Web'],
  ['FUNDICION CALLAO', 'Miraflores', 'Manufacture', 'Outdated', 'Legacy Modernization'],
  ['KOMFORT S.A.', 'San Borja', 'Manufacture', 'Absent', 'Full Web Build'],
  ['SERVICIOS IND. MARINA', 'Santiago de Surco', 'Manufacture', 'Absent', 'Tech Specs Portal'],
  ['DELCROSA SA', 'San Borja', 'Manufacture', 'Absent', 'Full Web Build'],
  ['ALIMENTOS SAN CHARBEL', 'San Borja', 'Food', 'Absent', 'Production Showcase'],
  ['COMERCIAL OLIMAR', 'San Borja', 'Trade', 'Absent', 'Trading Dashboard'],
  ['MAYORSA S.A.', 'Santiago de Surco', 'Trade', 'Outdated', 'Corporate Performance Build'],
  ['OLIVOS DEL SUR', 'La Molina/Lurin', 'Agri', 'Outdated', 'Brand Storytelling'],
  ['DISTRIBUIDORA NUGENT', 'San Borja', 'Trade', 'Absent', 'Full Web Build'],
  ['MI JATO S.A.C.', 'Miraflores', 'Services', 'Absent', 'Local Service Web'],
  ['CODVIL S.R.L.', 'San Borja', 'Trade', 'Absent', 'Business Services Site'],
  ['GRUPO JMC E.I.R.L.', 'San Borja', 'Trade', 'Absent', 'Professional Brand Build'],
  ['CONTINENTAL TRADING', 'San Isidro', 'Trade', 'Absent', 'International UX Build'],
  ['RIVERA SANTIVANEZ', 'San Isidro', 'Trade', 'Absent', 'Personal Brand Build'],
  ['MORI RUIZ SANCHEZ', 'San Borja', 'Services', 'Absent', 'Service Portal Build'],
  ['FASCINAS TEXTILES', 'San Borja', 'Textiles', 'Absent', 'Design-Forward Web'],
]

async function insertBatch(rows: Lead[]) {
  for (const r of rows) {
    await pool.query(
      `INSERT INTO crm_leads
         (name, district, niche, category, instagram_active, website_status, evaluation, strategic_action, potential)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       ON CONFLICT DO NOTHING`,
      [
        r.name,
        r.district,
        r.niche,
        r.category ?? null,
        r.instagram_active ?? null,
        r.website_status ?? null,
        r.evaluation ?? null,
        r.strategic_action ?? null,
        r.potential ?? null,
      ]
    )
  }
}

async function main() {
  const map = (
    arr: Array<[string, string, boolean, string, string, string]>,
    niche: string
  ): Lead[] =>
    arr.map(([name, district, ig, ws, ev, sa]) => ({
      name,
      district,
      niche,
      instagram_active: ig,
      website_status: ws,
      evaluation: ev,
      strategic_action: sa,
    }))

  const all: Lead[] = [
    ...map(gastronomy, 'Gastronomy'),
    ...map(legal, 'Professional Services'),
    ...map(beauty, 'Beauty & Wellness'),
    ...map(automotive, 'Automotive'),
    ...map(fitness, 'Fitness'),
    ...industrial.map(([name, district, category, ws, potential]) => ({
      name,
      district,
      niche: 'Industrial & Commercial',
      category,
      website_status: ws,
      evaluation: ws === 'Absent' ? 'Absent' : ws === 'Outdated' ? 'Outdated' : null,
      potential,
    })) as Lead[],
  ]

  console.log(`Seeding ${all.length} leads…`)
  await insertBatch(all)
  const { rows } = await pool.query('SELECT COUNT(*) FROM crm_leads')
  console.log(`✓ Done. crm_leads now contains ${rows[0].count} rows.`)
  await pool.end()
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
